name: Deploy to Preview
on:
  push:
    branches:
      - main
jobs:
  ftp-deploy:
    name: FTP Sync to cPanel
    runs-on: ubuntu-latest
    steps:
    - name: Get the latest code
      uses: actions/checkout@v4
    
    - name: Upload to Namecheap
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ./public_html/preview/
        
